blog/urls.py
from django.urls import path

from .views import index_view, blog_view, user_blog

app_name = 'blog'

urlpatterns = [
    path('', index_view, name='index'),
    path('blogs/', blog_view, name='blogs'),
    path('user/<int:pk>/', user_blog, name='user_blog')
]

django_root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

from datetime import timedelta


class User(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def created_at(self):
        return self.created + timedelta(minutes=45, hours=5)

    def updated_at(self):
        return self.updated + timedelta(minutes=45, hours=5)

blog/views.py
from django.shortcuts import render

from .models import Blog, User


# index_view
def index_view(request):
    return render(request, 'blog/index.html')


# blog_view
def blog_view(request):
    blogs = Blog.objects.all().order_by('-created')

    context = {'blogs': blogs}
    return render(request, 'blog/blogs.html', context=context)


def user_blog(request, pk):
    user_blog = Blog.objects.filter(user_id=pk)
    user_name = User.objects.filter(id=pk).first()

    context = {
        'user_blog': user_blog,
        'user_name': user_name
    }
    return render(request, 'blog/user_blog.html', context)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;1,400&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <title>Blog Landing Page</title>
</head>
<body>

        {% block content %}

        {% endblock content %}


</body>
</html>

blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}

{% block content %}
<a href="{% url 'blog:index' %}">
    <i class="fas fa-home"></i>
</a>
    <div class="container">
        <h1>Blogs</h1>
        {% for blog in blogs %}
        <div class="card">
            <div class="card-title">
                {{ blog.title }}
            </div>
            <div class="card-body">
                {{ blog.body }}
            </div>
            <div class="card-footer">
                <a href="#">
                <i class="fas fa-user" style="margin-right: .5em;"></i>{{ blog.user.name}} </a>

                <span>Created: {{ blog.created_at }}</span>
                <span>Last Updated: {{blog.updated_at}}</span>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container-blog">
    <h1>Welcome to Blog Landing Page.</h1>
    <p>Explore the blog world in your own way. Keep growing yourself by reading blog.</p>
    <a href="{% url 'blog:blogs' %}" class="btn blog-btn">
        Read Blogs
    </a>
</div>
{% endblock %}

blog/templates/blog/user_blog.html
{% extends 'blog/base.html' %}

{% block content %}
<a href="{% url 'blog:index' %}">
    <i class="fas fa-home"></i>
</a>
    <div class="container">
        <h1>{{ user_name }}</h1>
        {% for blog in user_blog %}
        <div class="card">
            <div class="card-title">
                {{ blog.title }}
            </div>
            <div class="card-body">
                {{ blog.body }}
            </div>
            <div class="card-footer">

                <i class="fas fa-user" style="margin-right: .5em;"></i>{{ blog.user.name}}

                <span>Created: {{ blog.created_at }}</span>
                <span>Last Updated: {{blog.updated_at}}</span>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}